# Generated by Django 4.1 on 2022-08-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("mobile", models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Usertype",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="HealthUserSessions",
            fields=[
                (
                    "health_user_session_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("token", models.CharField(max_length=100)),
                (
                    "healthuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.healthuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="healthuser",
            name="user_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="account.usertype"
            ),
        ),
    ]
