# Generated by Django 4.1 on 2022-08-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_healthuserotp_healthuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertype",
            name="user_category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="healthuser",
            name="mobile",
            field=models.IntegerField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="healthuser",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
