# Generated by Django 4.1 on 2022-08-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_usertype_user_category_alter_healthuser_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthuser",
            name="mobile",
            field=models.IntegerField(default=1234567890, max_length=10),
        ),
    ]
